apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-aws-secrets
  namespace: petclinic
spec:
  provider: aws
  parameters:
    region: ap-southeast-2
    objects: |
      - objectName: mydatabase/credentials
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: mysqlusername
          - path: password
            objectAlias: mysqlpassword
          - path: mysql_url
            objectAlias: mysql_url
          - path: root_password
            objectAlias: root_password
          - path: mysql_database
            objectAlias: mysql_database
  secretObjects:
    - secretName: db-k8s-secret
      type: Opaque
      data:
        - objectName: mysqlusername
          key: MYSQL_USER
        - objectName: mysqlpassword
          key: MYSQL_PASSWORD
        - objectName: mysql_url
          key: MYSQL_DATABASE
        - objectName: root_password
          key: MYSQL_ROOT_PASSWORD
        - objectName: mysql_database
          key: MYSQL_DATABASE
