apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app-backend-dev-deployment
  namespace: quiz-app-backend-dev
  labels:
    app: quiz-app-backend
    env: dev

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: quiz-app-backend
      env: dev
  template:
    metadata:
      labels:
        app: quiz-app-backend
        env: dev
    spec:
      serviceAccountName: secret-deployment-sa
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: quiz-app-backend-dev
          image: 587866558777.dkr.ecr.ap-southeast-2.amazonaws.com/quiz-app-backend-dev:852e2473675c013513ece1e1da954d483b961e89
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env: 
            - name: MONGO_URI
              value: "/mnt/secrets-store/MONGO_URI"
      volumes:
        - name: secrets-store-inline
          csi:
            driver: "secrets-store.csi.k8s.io"
            readOnly: true
            volumeAttributes:
              secretProviderClass: quiz-app-backend-secret-manager
          # env: 
          #   - name: MONGO_URI
          #     value: mongodb+srv://wangyaxu7:3Z9FqG4ZbDCXFUpL@quiz-app.037wdok.mongodb.net/?retryWrites=true&w=majority&appName=quiz-app
          # if app is able to  send trraffic or not
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
          # if container is up and running
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1