apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: adijaiswal/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              value: dv9fp4wrb
            - name: CLOUDINARY_KEY
              value: 124988194451598
            - name: CLOUDINARY_SECRET
              value: yXrzd149cFcxNpzgoW9LAqEsFFU
            - name: MAPBOX_TOKEN
              value: pk.eyJ1IjoiYmFybmV5d2FuZyIsImEiOiJjbHY3a3U2MGQwYm0wMmxvYTdhbWZndzl0In0.8L5Yl7U9yo4jjN_ib-JSaQ
            - name: DB_URL
              value: "mongodb+srv://wangyaxu7:jCCEblZhhimiIZ6q@devops.w9b5xtb.mongodb.net/?retryWrites=true&w=majority&appName=DevOps"
            - name: SECRET
              value: barney
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: demo
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer