apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-db
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io # force argocd to delete the kubernetes app first and then removes it from the argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Barney7777/petclinic-gitops.git
    targetRevision: devops-barney 
    path: petclinic/db
  destination: 
    server: https://kubernetes.default.svc
    namespace: petclinic

  syncPolicy:
    syncOptions:
    - CreateNamespace=true # to create a namespace if its not available

    automated: # we want argocd to automatically sync any changes in git repo, default is turned off. keeping 'automated' attribute will enable it.
      selfHeal: true # Changes made to the live cluster will not trigger automated sync. With this, it will only consider changes from the manifest files only from the git repository
      prune: true # if we rename or delete any component or for example delete the whol svc object in the cluster, we want argocd to delete in the cluster as well

# by default argocd will sync the changes every 3 mnutes, if you dont want this delay, then we can configure a git webhook between the git repo and argocd
