apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: petclinic
  labels:
    app: mysql-db
    tire: database

spec:
  selector:
    matchLabels:
      app: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:9.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER_NAME
          value: petclinic
        - name: MYSQL_USER_PASSWORD
          value: petclinic
        - name: MYSQL_DATABASE
          value: petclinic
