apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-db
    tier: database
spec:
  selector:
    app: mysql-db
    tier: database
  ports: 
    - port: 3306
      protocol: TCP
      targetPort: 3306
  