apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storage-class # The name of the StorageClass.
provisioner: ebs.csi.aws.com # The name of the AWS CSI driver.
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs # The filesystem type to format the volume.
  type: gp2 # The type of AWS EBS volume.
reclaimPolicy: Retain