apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: petclinic

spec:
  # replicas: 2 #if use hpa, don't use replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: petclinic-app
          image: 587866558777.dkr.ecr.ap-southeast-2.amazonaws.com/petclinic-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: petclinic
spec:
  selector:
    app: petclinic-app
  ports:
    - protocol: TCP
      port: 8080 #port inside cluster/dockerfile
      targetPort: 8080 # port exposed to the outside world
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-hpa
  namespace: petclinic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70