apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: petclinic
  labels:
    app: mysql-db
    tire: database

spec:
  selector:
    matchLabels:
      app: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:9.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER_NAME
          value: petclinic
        - name: MYSQL_USER_PASSWORD
          value: petclinic
        - name: MYSQL_DATABASE
          value: petclinic
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
    volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-db
    tier: database
spec:
  selector:
    app: mysql-db
    tier: database
  ports: 
    - port: 3306
      protocol: TCP
      targetPort: 3306
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storage-class # The name of the StorageClass.
provisioner: ebs.csi.aws.com # The name of the AWS CSI driver.
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs # The filesystem type to format the volume.
  type: gp2 # The type of AWS EBS volume.
reclaimPolicy: Retain

---
# Define a 'Persistent Voulume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc # name of PVC essential for identifying the storage data
  labels:
    app: mysql-db
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.