apiVersion: v1
kind: Service
metadata:
  name: mongo-db-dev-service
  namespace: quiz-app-db-dev
spec:
  selector:
    app: mongo-db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP