apiVersion: v1
kind: Service
metadata:
  name: quiz-app-backend-dev-service
  namespace: quiz-app-backend-dev
spec:
  selector:
    app: quiz-app-backend
  ports:
    - protocol: TCP
      port: 3000 # port in Dockerfile
      targetPort: 3000
  type: ClusterIP
