apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: quiz-app-frontend-dev
type: Opaque
data:
  VITE_REACT_APP_API_UR: aHR0cHM6Ly9iYWNrZW5kLmJhcm5leXdhbmcuY2xpY2svYXBpL3F1ZXN0aW9ucwo=