apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-db-dev-pv
  namespace: quiz-app-db-dev
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db